# Generated by Django 2.0.2 on 2019-12-17 10:38
import os
import pathlib

from django.conf import settings
from django.db import migrations
from django.db.migrations.executor import MigrationExecutor


BASE_DIR = os.path.join(settings.BASE_DIR, 'content_library', 'migrations')

def forwards_func(apps, schema_editor):
    connection = schema_editor.connection
    path = pathlib.Path(os.path.join(BASE_DIR, '05010_auto_20191213_2026.py'))
    if path.exists():
        # Reverse to the original migration
        executor = MigrationExecutor(connection)
        executor.migrate([('content_library', '0509_auto_20191209_2026')])

        # Rename the file
        post_migration_path = pathlib.Path(os.path.join(BASE_DIR, '0511_auto_20191213_1721.py'))
        output = post_migration_path.read_text().replace('05010_auto_20191213_2026', '0510_auto_20191213_2026')
        post_migration_path.write_text(output)

        path.rename(os.path.join(BASE_DIR, '0510_auto_20191213_2026.py'))

        # Reapply the migration
        executor = MigrationExecutor(connection)
        executor.loader.build_graph()  # reload.
        executor.migrate([('content_library', '0515_auto_20191217_1038')])


class Migration(migrations.Migration):

    dependencies = [
        ('content_library', '0514_clientconfiguration_spa_enabled_for_nonstaff'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]


